package com.muneeb.coursemanager.ui.theme

import androidx.compose.ui.graphics.Color

// Monochrome palette (base constants)
val AppBlack = Color(0xFF1A1A1A)
val AppWhite = Color(0xFFFFFFFF)
val AppGrey = Color(0xFF9E9E9E)
val DarkBackground = Color(0xFF000000)
val DarkSurface = Color(0xFF000000)

// Monochrome accent card — non-inverting
val MonochromeDarkAccentCard = Color(0xFF00000)

// Monochrome countdown/urgency red — vivid, NOT the muted ErrorLight
val MonochromeCountdownRed = Color(0xFFE53935)

// Pink palette — light
val PinkLightBackground = Color(0xFFFFF0F5)
val PinkLightPrimary = Color(0xFFE91E63)
val PinkLightOnPrimary = Color(0xFFFFFFFF)
val PinkLightPrimaryContainer = Color(0xFFFCE4EC)
val PinkLightOnPrimaryContainer = Color(0xFF3E0A1E)
val PinkLightSecondary = Color(0xFFC2185B)
val PinkLightOnSecondary = Color(0xFFFFFFFF)
val PinkLightSecondaryContainer = Color(0xFFF8BBD0)
val PinkLightOnSecondaryContainer = Color(0xFF3E0A1E)
val PinkLightTertiary = Color(0xFFAD1457)
val PinkLightOnTertiary = Color(0xFFFFFFFF)
val PinkLightTertiaryContainer = Color(0xFFF48FB1)
val PinkLightOnTertiaryContainer = Color(0xFF3E0A1E)
val PinkLightOnBackground = Color(0xFF2B2B2B)
val PinkLightOnSurface = Color(0xFF2B2B2B)
val PinkLightSurfaceVariant = Color(0xFFFCE4EC)
val PinkLightOnSurfaceVariant = Color(0xFF6B4A55)
val PinkLightOutline = Color(0xFF8A6A75)
val PinkLightOutlineVariant = Color(0xFFE0BCC7)
val PinkLightInverseSurface = Color(0xFF2B2B2B)
val PinkLightInverseOnSurface = Color(0xFFFFF0F5)
val PinkLightInversePrimary = Color(0xFFF48FB1)

// Pink palette — dark (containers lightened for contrast against near-black bg)
val PinkDarkBackground = Color(0xFF1A0E14)
val PinkDarkSurface = Color(0xFF1A0E14)
val PinkDarkPrimary = Color(0xFFF48FB1)
val PinkDarkOnPrimary = Color(0xFF3E0A1E)
val PinkDarkPrimaryContainer = Color(0xFFF8BBD0)
val PinkDarkOnPrimaryContainer = Color(0xFF3E0A1E)
val PinkDarkSecondary = Color(0xFFF8BBD0)
val PinkDarkOnSecondary = Color(0xFF3E0A1E)
val PinkDarkSecondaryContainer = Color(0xFFFCE4EC)
val PinkDarkOnSecondaryContainer = Color(0xFF3E0A1E)
val PinkDarkTertiary = Color(0xFFF48FB1)
val PinkDarkOnTertiary = Color(0xFF3E0A1E)
val PinkDarkTertiaryContainer = Color(0xFFF48FB1)
val PinkDarkOnTertiaryContainer = Color(0xFF3E0A1E)
val PinkDarkOnBackground = Color(0xFFF5E6ED)
val PinkDarkOnSurface = Color(0xFFF5E6ED)
val PinkDarkSurfaceVariant = Color(0xFF3E2231)
val PinkDarkOnSurfaceVariant = Color(0xFFD4B4C0)
val PinkDarkOutline = Color(0xFF8A6A75)
val PinkDarkOutlineVariant = Color(0xFF4A2A38)
val PinkDarkInverseSurface = Color(0xFFF5E6ED)
val PinkDarkInverseOnSurface = Color(0xFF1A0E14)
val PinkDarkInversePrimary = Color(0xFFE91E63)

// Pink accent card — non-inverting
val PinkLightAccentCard = Color(0xFF6B1A3A)
val PinkDarkAccentCard = Color(0xFF3A1A28)

// Pink countdown/urgency color — leans red-pink, distinct from PinkLightPrimary
val PinkLightCountdown = Color(0xFFD81B60)
val PinkDarkCountdown = Color(0xFFD81B60)

// Slate palette — light (Claude-like warm grey, no orange/terracotta)
val SlateLightBackground = Color(0xFFFAF9F7)
val SlateLightPrimary = Color(0xFF5C5C5C)
val SlateLightOnPrimary = Color(0xFFFAF9F7)
val SlateLightPrimaryContainer = Color(0xFFEDEBE8)
val SlateLightOnPrimaryContainer = Color(0xFF2B2B2B)
val SlateLightSecondary = Color(0xFF6E6E6E)
val SlateLightOnSecondary = Color(0xFFFAF9F7)
val SlateLightSecondaryContainer = Color(0xFFE5E3DF)
val SlateLightOnSecondaryContainer = Color(0xFF2B2B2B)
val SlateLightTertiary = Color(0xFF7A7A7A)
val SlateLightOnTertiary = Color(0xFFFAF9F7)
val SlateLightTertiaryContainer = Color(0xFFDDDBD7)
val SlateLightOnTertiaryContainer = Color(0xFF2B2B2B)
val SlateLightOnBackground = Color(0xFF2B2B2B)
val SlateLightOnSurface = Color(0xFF2B2B2B)
val SlateLightSurfaceVariant = Color(0xFFEDEBE8)
val SlateLightOnSurfaceVariant = Color(0xFF5C5C5C)
val SlateLightOutline = Color(0xFF8A8A8A)
val SlateLightOutlineVariant = Color(0xFFC9C7C3)
val SlateLightInverseSurface = Color(0xFF2B2B2B)
val SlateLightInverseOnSurface = Color(0xFFFAF9F7)
val SlateLightInversePrimary = Color(0xFFB0B0B0)

// Slate palette — dark (charcoal, not pure black; containers lightened)
val SlateDarkBackground = Color(0xFF232323)
val SlateDarkSurface = Color(0xFF2A2A2A)
val SlateDarkPrimary = Color(0xFFB0B0B0)
val SlateDarkOnPrimary = Color(0xFF232323)
val SlateDarkPrimaryContainer = Color(0xFFE5E3DF)
val SlateDarkOnPrimaryContainer = Color(0xFF2B2B2B)
val SlateDarkSecondary = Color(0xFFA0A0A0)
val SlateDarkOnSecondary = Color(0xFF232323)
val SlateDarkSecondaryContainer = Color(0xFFEDEBE8)
val SlateDarkOnSecondaryContainer = Color(0xFF2B2B2B)
val SlateDarkTertiary = Color(0xFF909090)
val SlateDarkOnTertiary = Color(0xFF232323)
val SlateDarkTertiaryContainer = Color(0xFFDDDBD7)
val SlateDarkOnTertiaryContainer = Color(0xFF2B2B2B)
val SlateDarkOnBackground = Color(0xFFE8E6E3)
val SlateDarkOnSurface = Color(0xFFE8E6E3)
val SlateDarkSurfaceVariant = Color(0xFF353535)
val SlateDarkOnSurfaceVariant = Color(0xFFB8B8B8)
val SlateDarkOutline = Color(0xFF8A8A8A)
val SlateDarkOutlineVariant = Color(0xFF404040)
val SlateDarkInverseSurface = Color(0xFFE8E6E3)
val SlateDarkInverseOnSurface = Color(0xFF232323)
val SlateDarkInversePrimary = Color(0xFF5C5C5C)

// Slate accent card — non-inverting
val SlateLightAccentCard = Color(0xFF2B2B2B)
val SlateDarkAccentCard = Color(0xFF3A3A3A)

// Slate countdown/urgency red — same vivid red as Monochrome
val SlateCountdownRed = Color(0xFFE53935)

// Shared error roles
val ErrorLight = Color(0xFFB3261E)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFF9DEDC)
val OnErrorContainerLight = Color(0xFF410E0B)
val ErrorDark = Color(0xFFF2B8B5)
val OnErrorDark = Color(0xFF601410)
val ErrorContainerDark = Color(0xFF8C1D18)
val OnErrorContainerDark = Color(0xFFF9DEDC)